name: Translate PDF with Python
on:
  push:
    paths:
      - 'papers/*.pdf'
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdf2zh
      - name: Translate all PDFs in papers/
        run: |
          mkdir -p translation_output archive
          pdf2zh --dir papers/ -o translation_output -s openai
          mv papers/*.pdf archive/
      - name: Commit and Push Translated Files + Archived PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add translation_output/*.pdf archive/*.pdf
          
          # Stash changes to ensure no conflict when pulling
          git stash || echo "No local changes to stash"

          git commit -m "Auto translate PDF and archive originals" || echo "No changes to commit"

          # Pull with rebase to avoid conflicts
          git pull origin main --rebase || exit 1

          # Apply the stashed changes and commit them
          git stash pop || echo "No changes to apply from stash"

          # Add any unstaged changes from the stash
          git add .

          # Commit and Push
          git commit -m "Reapply stashed changes" || echo "No changes to commit"

          # Retry push if failed
          for i in 1 2 3; do
            git push origin main && break
            echo "Push failed, retrying in 5 seconds... ($i)"
            sleep 5
            git pull origin main --rebase || break
          done